version: "3.7"
services:
  #imagem micro e-mail
  micro-mail:
    build: 
      args:
        user: carlos
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes: 
      - ./:var/www
    depends_on:
      - redis_micro_email
      - queue
    networks:
      - micromail

  #ngnix
  ngnix:
    image: ngnix:alpine
    restart: unless-stopped
    ports:
      - 8005:80
    volumes:
      - ./:var/www
      - ./docker/ngnix/:etc/ngnix/conf.d
    networks:
      - micromail

  # queue micro email
  queue:
    build: 
      args:
        user: carlos
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
      - ./:var/www
    networks:
      - micromail

  #redis
  redis_micro_email:
    image: redis:latest
    networks:
      - micromail

networks:
  micromail:
    driver: bridge